name: Trigger auto deployment for contosoairdemo2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/contosoairdemo2-AutoDeployTrigger-3e85ded1-0f99-42a4-ba0f-ed1de4fe0ede.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTOSOAIRDEMO2_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ca5b9f5c6b05acr.azurecr.io
          registryUsername: ${{ secrets.CONTOSOAIRDEMO2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTOSOAIRDEMO2_REGISTRY_PASSWORD }}
          containerAppName: contosoairdemo2
          resourceGroup: bcd-contosoairdemo-rg
          imageToBuild: ca5b9f5c6b05acr.azurecr.io/contosoairdemo2:${{ github.sha }}
          

     

